import {
  Avatar,
  Bell,
  Briefcase,
  Calendar,
  ChatLineSquare,
  Checked,
  Clock,
  Coin,
  CollectionTag,
  Connection,
  CreditCard,
  DataAnalysis,
  DataBoard,
  DataLine,
  Document,
  DocumentChecked,
  Files,
  FirstAidKit,
  Histogram,
  Link,
  List,
  Location,
  Lock,
  Money,
  Odometer,
  OfficeBuilding,
  Operation,
  Opportunity,
  PieChart,
  PriceTag,
  Promotion,
  SetUp,
  Setting,
  Tools,
  TrendCharts,
  Tickets,
  User,
  UserFilled,
  Wallet,
  WalletFilled,
  Warning,
} from '@element-plus/icons-vue'

const appRouteSections = [
  {
    label: 'Dashboard',
    items: [
      {
        title: '總覽',
        name: 'dashboard-overview',
        path: 'dashboard/overview',
        icon: Odometer,
        component: () => import('../views/dashboard/OverviewView.vue'),
      },
      {
        title: '營收概況',
        name: 'dashboard-revenue-overview',
        path: 'dashboard/revenue-overview',
        icon: DataLine,
        component: () => import('../views/dashboard/RevenueOverviewView.vue'),
      },
      {
        title: '商機概況',
        name: 'dashboard-opportunity-overview',
        path: 'dashboard/opportunity-overview',
        icon: Opportunity,
        component: () => import('../views/dashboard/OpportunityOverviewView.vue'),
      },
      {
        title: '夥伴績效',
        name: 'dashboard-partner-performance',
        path: 'dashboard/partner-performance',
        icon: Histogram,
        component: () => import('../views/dashboard/PartnerPerformanceView.vue'),
      },
      {
        title: '風險預警',
        name: 'dashboard-risk-alerts',
        path: 'dashboard/risk-alerts',
        icon: Warning,
        component: () => import('../views/dashboard/RiskAlertsView.vue'),
      },
    ],
  },
  {
    label: '客戶管理',
    items: [
      {
        title: '客戶列表',
        name: 'accounts-list',
        path: 'accounts/list',
        icon: OfficeBuilding,
        component: () => import('../views/accounts/AccountListView.vue'),
      },
      {
        title: '聯絡人',
        name: 'accounts-contacts',
        path: 'contacts',
        icon: User,
        component: () => import('../views/accounts/ContactsView.vue'),
      },
      {
        title: '客戶分級',
        name: 'accounts-segmentation',
        path: 'accounts/tier',
        alias: ['accounts/segmentation'],
        icon: CollectionTag,
        component: () => import('../views/accounts/AccountSegmentationView.vue'),
      },
      {
        title: '客戶聯絡',
        name: 'accounts-engagement',
        path: 'accounts/engagement',
        alias: ['accounts/timeline'],
        icon: List,
        component: () => import('../views/accounts/AccountTimelineView.vue'),
      },
      {
        title: '客戶標籤',
        name: 'accounts-tags',
        path: 'accounts/tags',
        icon: PriceTag,
        component: () => import('../views/accounts/AccountTagsView.vue'),
      },
    ],
  },
  {
    label: '商機管理',
    items: [
      {
        title: '商機列表',
        name: 'opportunities-list',
        path: 'opportunities',
        alias: ['opportunities/list'],
        icon: Opportunity,
        component: () => import('../views/opportunities/OpportunityListView.vue'),
      },
      {
        title: 'Pipeline',
        name: 'opportunities-pipeline',
        path: 'opportunities/pipeline',
        icon: DataBoard,
        component: () => import('../views/opportunities/PipelineView.vue'),
      },
      {
        title: 'Forecast',
        name: 'opportunities-forecast',
        path: 'opportunities/forecast',
        icon: TrendCharts,
        component: () => import('../views/opportunities/ForecastView.vue'),
      },
      {
        title: '報價管理',
        name: 'opportunities-quotes',
        path: 'opportunities/quotes',
        icon: Tickets,
        component: () => import('../views/opportunities/QuoteManagementView.vue'),
      },
      {
        title: '合約管理',
        name: 'opportunities-contracts',
        path: 'opportunities/contracts',
        icon: Document,
        component: () => import('../views/opportunities/ContractManagementView.vue'),
      },
    ],
  },
  {
    label: '夥伴管理',
    items: [
      {
        title: '夥伴列表',
        name: 'partners-list',
        path: 'partners/list',
        icon: Briefcase,
        component: () => import('../views/partners/PartnerListView.vue'),
      },
      {
        title: '合作條件',
        name: 'partners-terms',
        path: 'partners/terms',
        icon: DocumentChecked,
        component: () => import('../views/partners/PartnershipTermsView.vue'),
      },
      {
        title: '通路績效',
        name: 'partners-channel-performance',
        path: 'partners/channel-performance',
        icon: Histogram,
        component: () => import('../views/partners/ChannelPerformanceView.vue'),
      },
      {
        title: '分潤管理',
        name: 'partners-settlement',
        path: 'partners/settlement',
        icon: Wallet,
        component: () => import('../views/partners/PartnerSettlementView.vue'),
      },
      {
        title: '夥伴入口',
        name: 'partners-portal',
        path: 'partners/portal',
        icon: Connection,
        component: () => import('../views/partners/PartnerPortalView.vue'),
      },
    ],
  },
  {
    label: '專案與活動',
    items: [
      {
        title: '專案列表',
        name: 'projects-list',
        path: 'projects/list',
        icon: Files,
        component: () => import('../views/projects/ProjectListView.vue'),
      },
      {
        title: '任務追蹤',
        name: 'projects-tasks',
        path: 'projects/tasks',
        icon: Checked,
        component: () => import('../views/projects/TaskTrackingView.vue'),
      },
      {
        title: '里程碑',
        name: 'projects-milestones',
        path: 'projects/milestones',
        icon: Calendar,
        component: () => import('../views/projects/MilestonesView.vue'),
      },
      {
        title: '行銷活動',
        name: 'projects-campaigns',
        path: 'projects/campaigns',
        icon: Promotion,
        component: () => import('../views/projects/CampaignsView.vue'),
      },
      {
        title: '文件中心',
        name: 'projects-documents',
        path: 'projects/documents',
        icon: Files,
        component: () => import('../views/projects/DocumentCenterView.vue'),
      },
    ],
  },
  {
    label: '互動與支援',
    items: [
      {
        title: '會議紀錄',
        name: 'engagement-meetings',
        path: 'engagement/meetings',
        icon: ChatLineSquare,
        component: () => import('../views/engagement/MeetingRecordsView.vue'),
      },
      {
        title: '拜訪紀錄',
        name: 'engagement-visits',
        path: 'engagement/visits',
        icon: Location,
        component: () => import('../views/engagement/VisitRecordsView.vue'),
      },
      {
        title: 'Email / 通話',
        name: 'engagement-communications',
        path: 'engagement/communications',
        icon: Bell,
        component: () => import('../views/engagement/CommunicationLogsView.vue'),
      },
      {
        title: '客訴 / Issue',
        name: 'engagement-issues',
        path: 'engagement/issues',
        icon: FirstAidKit,
        component: () => import('../views/engagement/IssuesView.vue'),
      },
      {
        title: 'Timeline',
        name: 'engagement-timeline',
        path: 'engagement/timeline',
        icon: Clock,
        component: () => import('../views/engagement/TimelineView.vue'),
      },
    ],
  },
  {
    label: '財務與結算',
    items: [
      {
        title: '營收資料',
        name: 'finance-revenue-records',
        path: 'finance/revenue-records',
        icon: Coin,
        component: () => import('../views/finance/RevenueRecordsView.vue'),
      },
      {
        title: '對帳管理',
        name: 'finance-reconciliation',
        path: 'finance/reconciliation',
        icon: SetUp,
        component: () => import('../views/finance/ReconciliationView.vue'),
      },
      {
        title: '分潤管理',
        name: 'finance-profit-sharing',
        path: 'finance/profit-sharing',
        icon: WalletFilled,
        component: () => import('../views/finance/ProfitSharingView.vue'),
      },
      {
        title: '發票 / 收付款',
        name: 'finance-billing-payments',
        path: 'finance/billing-payments',
        icon: CreditCard,
        component: () => import('../views/finance/BillingPaymentsView.vue'),
      },
      {
        title: '匯率與幣別',
        name: 'finance-currencies',
        path: 'finance/currencies',
        icon: Money,
        component: () => import('../views/finance/CurrenciesView.vue'),
      },
    ],
  },
  {
    label: '報表中心',
    items: [
      {
        title: '客戶分析',
        name: 'reports-customers',
        path: 'reports/customers',
        icon: PieChart,
        component: () => import('../views/reports/CustomerAnalyticsView.vue'),
      },
      {
        title: '商機分析',
        name: 'reports-opportunities',
        path: 'reports/opportunities',
        icon: DataAnalysis,
        component: () => import('../views/reports/OpportunityAnalyticsView.vue'),
      },
      {
        title: '營收分析',
        name: 'reports-revenue',
        path: 'reports/revenue',
        icon: DataLine,
        component: () => import('../views/reports/RevenueAnalyticsView.vue'),
      },
      {
        title: '分潤分析',
        name: 'reports-settlement',
        path: 'reports/settlement',
        icon: Wallet,
        component: () => import('../views/reports/SettlementAnalyticsView.vue'),
      },
      {
        title: '夥伴績效',
        name: 'reports-partners',
        path: 'reports/partners',
        icon: Histogram,
        component: () => import('../views/reports/PartnerAnalyticsView.vue'),
      },
      {
        title: '流失預警',
        name: 'reports-churn-alerts',
        path: 'reports/churn-alerts',
        icon: Bell,
        component: () => import('../views/reports/ChurnAlertsView.vue'),
      },
    ],
  },
  {
    label: '設定',
    items: [
      {
        title: '權限與角色',
        name: 'settings-permissions',
        path: 'settings/permissions',
        icon: Lock,
        component: () => import('../views/settings/PermissionsRolesView.vue'),
      },
      {
        title: '部門與使用者',
        name: 'settings-users',
        path: 'settings/users',
        icon: Avatar,
        component: () => import('../views/settings/DepartmentsUsersView.vue'),
      },
      {
        title: '流程自動化',
        name: 'settings-automation',
        path: 'settings/automation',
        icon: Operation,
        component: () => import('../views/settings/WorkflowAutomationView.vue'),
      },
      {
        title: '系統整合',
        name: 'settings-integrations',
        path: 'settings/integrations',
        icon: Connection,
        component: () => import('../views/settings/SystemIntegrationsView.vue'),
      },
      {
        title: 'API 管理',
        name: 'settings-api',
        path: 'settings/api',
        icon: Link,
        component: () => import('../views/settings/ApiManagementView.vue'),
      },
      {
        title: 'Dashboard 設定',
        name: 'settings-dashboard',
        path: 'settings/dashboard',
        icon: Setting,
        component: () => import('../views/settings/DashboardSettingsView.vue'),
      },
      {
        title: '參數設定',
        name: 'settings-parameters',
        path: 'settings/parameters',
        icon: Tools,
        component: () => import('../views/settings/ParameterSettingsView.vue'),
      },
    ],
  },
]

const defaultAppItem = appRouteSections[0].items[0]
const defaultAppPath = `/${defaultAppItem.path}`
const defaultAppTag = {
  name: defaultAppItem.name,
  title: defaultAppItem.title,
  path: defaultAppPath,
  fullPath: defaultAppPath,
  affix: true,
}

const appChildRoutes = appRouteSections.flatMap((section) =>
  section.items.map((item) => ({
    path: item.path,
    name: item.name,
    component: item.component,
    ...(item.alias ? { alias: item.alias } : {}),
    meta: {
      title: item.title,
      section: section.label,
      icon: item.icon,
      affix: item.path === defaultAppItem.path,
      keepAlive: true,
    },
  })),
)

const authRoutes = [
  {
    path: 'login',
    name: 'login',
    component: () => import('../views/auth/LoginView.vue'),
    meta: {
      title: '登入',
      section: 'Auth',
    },
  },
]

const appUtilityRoutes = [
  {
    path: 'opportunities/:opportunityId',
    name: 'opportunity-detail',
    component: () => import('../views/opportunities/OpportunityDetailView.vue'),
    meta: {
      title: '商機管理 / 詳情',
      section: '商機管理',
      icon: Opportunity,
      keepAlive: true,
    },
  },
  {
    path: 'accounts/:accountId',
    name: 'account-detail',
    component: () => import('../views/accounts/AccountDetailView.vue'),
    meta: {
      title: '客戶列表 / 詳情',
      section: '客戶管理',
      icon: OfficeBuilding,
      keepAlive: true,
    },
  },
  {
    path: 'opportunities/contracts/:contractId',
    name: 'contract-detail',
    component: () => import('../views/opportunities/ContractDetailView.vue'),
    meta: {
      title: '合約管理 / 詳情',
      section: '商機管理',
      icon: Document,
      keepAlive: true,
    },
  },
  {
    path: 'profile/center',
    name: 'profile-center',
    component: () => import('../views/profile/ProfileCenterView.vue'),
    meta: {
      title: '個人中心',
      section: '帳號中心',
      icon: UserFilled,
      keepAlive: true,
    },
  },
  {
    path: 'partners/terms/:termId',
    name: 'partners-term-detail',
    component: () => import('../views/partners/PartnershipTermDetailView.vue'),
    meta: {
      title: '合作條件 / 詳情',
      section: '夥伴管理',
      icon: DocumentChecked,
      keepAlive: true,
    },
  },
  {
    path: 'partners/channel-performance/:partnerId',
    name: 'partners-channel-performance-detail',
    component: () => import('../views/partners/ChannelPerformanceDetailView.vue'),
    meta: {
      title: '通路績效 / 詳情',
      section: '夥伴管理',
      icon: Histogram,
      keepAlive: true,
    },
  },
  {
    path: 'partners/settlement/:settlementId',
    name: 'partners-settlement-detail',
    component: () => import('../views/partners/PartnerSettlementDetailView.vue'),
    meta: {
      title: '分潤管理 / 詳情',
      section: '夥伴管理',
      icon: Wallet,
      keepAlive: true,
    },
  },
  {
    path: 'partners/portal/:portalId',
    name: 'partners-portal-detail',
    component: () => import('../views/partners/PartnerPortalDetailView.vue'),
    meta: {
      title: '夥伴入口 / 詳情',
      section: '夥伴管理',
      icon: Connection,
      keepAlive: true,
    },
  },
]

export {
  appRouteSections,
  appChildRoutes,
  appUtilityRoutes,
  authRoutes,
  defaultAppTag,
  defaultAppPath,
}
